#!/bin/bash
# Author: Iain Douglas <centos@1n6.org.uk>
t_Log "Running $0 group add tests"

# Delete any info from previous runs, use sed because we haven't yet tested
# groupdel
sed -i /testgroup/d /etc/group

echo "Create a new group"
next_guid=$((10+$(awk -F: '{print $3}' /etc/group | sort | tail -1)))
groupadd -g $next_guid testgroup
t_CheckExitStatus $?
